export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_DATA_REQUEST_REQUEST = 'USER_DATA_REQUEST_REQUEST';
export const USER_DATA_REQUEST_SUCCESS = 'USER_DATA_REQUEST_SUCCESS';
export const USER_DATA_REQUEST_FAIL = 'USER_DATA_REQUEST_FAIL';

export const GITHUB_USER_REQUEST_REQUEST = 'GITHUB_USER_REQUEST_REQUEST';
export const GITHUB_USER_REQUEST_SUCCESS = 'GITHUB_USER_REQUEST_SUCCESS';
export const GITHUB_USER_REQUEST_FAIL = 'GITHUB_USER_REQUEST_FAIL';
