const testDB = [
    {
        id: 1,
        title: 'api-design-with-djangorest',
        description: 'Api design with django framework',
        language: 'Python',
        starRating: 1,
        timeStamp: 5,
    },
    {
        id: 2,
        title: 'api-design-with-flask',
        description: 'Api design with flask framework',
        language: 'Python',
        starRating: 2,
        timeStamp: 2,
    },
    {
        id: 3,
        title: 'api-design-with-node',
        description: 'Api design with javascript framework',
        language: 'Javascript',
        starRating: 5,
        timeStamp: 3,
    },
    {
        id: 4,
        title: 'api-design-with-deno',
        description: 'Api design with javascript framework',
        language: 'Javascript',
        starRating: 6,
        timeStamp: 4,
    },
    {
        id: 5,
        title: 'Indeego-web-app',
        description: 'Web application for Indeego restaurant and lounge',
        language: 'Javascript',
        starRating: 7,
        timeStamp: 5,
    },
    {
        id: 6,
        title: 'Bitmama-Github-Task',
        description: 'A web application project development task to test my skill set in the fields of react js, state management and HTTP request',
        language: 'Javascript',
        starRating: 8,
        timeStamp: 6,
    },
    {
        id: 7,
        title: 'indeego-mobile-app',
        description: 'Mobile application for Indeego restaurant and lounge',
        language: 'Javascript',
        starRating: 9,
        timeStamp: 7,
    },
    {
        id: 8,
        title: 'mentor-town-frontend',
        description: 'Forked from Adtrex/mentor-town-frontend',
        language: 'Javascript',
        starRating: 10,
        timeStamp: 8,
    },
    {
        id: 9,
        title: 'Boom-Pay',
        description: 'Financial technology mobile application software, frontend built with react native',
        language: 'Javascript',
        starRating: 11,
        timeStamp: 9,
    },
    {
        id: 10,
        title: 'ivory-cloudify-frontend-reactjs',
        description: 'Frontend Ivory Cloudify Electronic Medical Record Software',
        language: 'Javascript',
        starRating: 12,
        timeStamp: 10,
    },
    {
        id: 11,
        title: 'ivory-cloudify-frontend-reactjs',
        description: 'Frontend Ivory Cloudify Electronic Medical Record Software',
        language: 'Javascript',
        starRating: 12,
        timeStamp: 10,
    },
    {
        id: 12,
        title: 'fullstack-ecommerce-app',
        description: 'Full stack ecommerce web app implementing mongo database, express J.S, react J.S and node J.S',
        language: 'Python',
        starRating: 13,
        timeStamp: 12,
    },
    {
        id: 13,
        title: 'trinipicks-users-frontend',
        description: 'Sports betting web app, using crypto as payment',
        language: 'Python',
        starRating: 14,
        timeStamp: 13,
    },
    {
        id: 14,
        title: 'Budget-Tracker-Web-App',
        description: 'This is a basic budget web application built with HTML 5, CSS 3 and Vanilla javascript',
        language: 'Javascript',
        starRating: 15,
        timeStamp: 14,
    },
    {
        id: 15,
        title: 'react-native-contacts-app',
        description: 'mobile app built with react native',
        language: 'Javascript',
        starRating: 16,
        timeStamp: 15,
    },
    {
        id: 16,
        title: 'react-native-expo-number-guesser-game-app',
        description: 'number guessing mobile app built with expo react native',
        language: 'Javascript',
        starRating: 17,
        timeStamp: 16,
    }, 
    {
        id: 17,
        title: 'ivory-cloud-backend',
        description: 'number guessing mobile app built with expo react native',
        language: 'Javascript',
        starRating: 18,
        timeStamp: 16,
    },
    {
        id: 18,
        title: 'Easylearn-api',
        description: 'backend app',
        language: 'Python',
        starRating: 19,
        timeStamp: 18,
    },
    {
        id: 19,
        title: 'node-first-chat-app',
        description: 'backend app',
        language: 'Javascript',
        starRating: 20,
        timeStamp: 19,
    },
    {
        id: 20,
        title: 'node-first-chat-app',
        description: 'backend app',
        language: 'Javascript',
        starRating: 20,
        timeStamp: 19,
    },
];

export default testDB;